# Generated by Django 6.0.4 on 2026-08-16 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrepreneur',
            old_name='bio',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='entrepreneur',
            old_name='linkedin',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='entrepreneur',
            old_name='twitter',
            new_name='youtube',
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='workimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
