# Generated by Django 6.0.4 on 2026-08-18 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0002_rename_bio_entrepreneur_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='entrepreneurs.entrepreneur')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('entrepreneur', 'visitor_id'), name='unique_entrepreneur_visitor_like')],
            },
        ),
    ]
