# Generated by Django 6.0.4 on 2026-08-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0003_entrepreneurlike'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entrepreneurlike',
            index=models.Index(fields=['entrepreneur', 'visitor_id'], name='entrepreneur_visitor_idx'),
        ),
    ]
