# Generated by Django 6.0.4 on 2026-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0004_entrepreneurlike_entrepreneur_visitor_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='linkedIn',
            field=models.URLField(blank=True),
        ),
    ]
