# Generated by Django 6.0.4 on 2026-08-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0005_entrepreneur_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrepreneur',
            old_name='linkedIn',
            new_name='linkedin',
        ),
    ]
